apiVersion: coralogix.com/v1alpha1
kind: RecordingRuleGroupSet
metadata:
  labels:
    app.kubernetes.io/name: recordingrulegroupset
    app.kubernetes.io/instance: recordingrulegroupset-sample
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator-poc
  name: recordingrulegroupset-sample
spec:
  # TODO(user): Add fields here
