apiVersion: coralogix.coralogix/v1
kind: RecordingRuleGroup
metadata:
  labels:
    app.kubernetes.io/name: recordingrulegroup
    app.kubernetes.io/instance: recordingrulegroup-sample
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator-poc
  name: recordingrulegroup-sample
spec:
  name: "name"
  intervalSeconds: 180
  rules:
    - record: "ts3db_live_ingester_write_latency:3m"
      expr: "sum(rate(ts3db_live_ingester_write_latency_seconds_count{CX_LEVEL=\"staging\",pod=~\"ts3db-live-ingester.*\"}[2m])) by (pod)"
    - record: "job:http_requests_total:sum"
      expr: "sum(rate(http_requests_total[5m])) by (job)"
