//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Block) DeepCopyInto(out *Block) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Block.
func (in *Block) DeepCopy() *Block {
	if in == nil {
		return nil
	}
	out := new(Block)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extract) DeepCopyInto(out *Extract) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extract.
func (in *Extract) DeepCopy() *Extract {
	if in == nil {
		return nil
	}
	out := new(Extract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtractTimestamp) DeepCopyInto(out *ExtractTimestamp) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtractTimestamp.
func (in *ExtractTimestamp) DeepCopy() *ExtractTimestamp {
	if in == nil {
		return nil
	}
	out := new(ExtractTimestamp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonExtract) DeepCopyInto(out *JsonExtract) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonExtract.
func (in *JsonExtract) DeepCopy() *JsonExtract {
	if in == nil {
		return nil
	}
	out := new(JsonExtract)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonStringify) DeepCopyInto(out *JsonStringify) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonStringify.
func (in *JsonStringify) DeepCopy() *JsonStringify {
	if in == nil {
		return nil
	}
	out := new(JsonStringify)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parse) DeepCopyInto(out *Parse) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parse.
func (in *Parse) DeepCopy() *Parse {
	if in == nil {
		return nil
	}
	out := new(Parse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParseJsonField) DeepCopyInto(out *ParseJsonField) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParseJsonField.
func (in *ParseJsonField) DeepCopy() *ParseJsonField {
	if in == nil {
		return nil
	}
	out := new(ParseJsonField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveFields) DeepCopyInto(out *RemoveFields) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
	if in.ExcludedFields != nil {
		in, out := &in.ExcludedFields, &out.ExcludedFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveFields.
func (in *RemoveFields) DeepCopy() *RemoveFields {
	if in == nil {
		return nil
	}
	out := new(RemoveFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replace) DeepCopyInto(out *Replace) {
	*out = *in
	in.RuleParams.DeepCopyInto(&out.RuleParams)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replace.
func (in *Replace) DeepCopy() *Replace {
	if in == nil {
		return nil
	}
	out := new(Replace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rule) DeepCopyInto(out *Rule) {
	*out = *in
	if in.Parse != nil {
		in, out := &in.Parse, &out.Parse
		*out = new(Parse)
		(*in).DeepCopyInto(*out)
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = new(Block)
		(*in).DeepCopyInto(*out)
	}
	if in.JsonExtract != nil {
		in, out := &in.JsonExtract, &out.JsonExtract
		*out = new(JsonExtract)
		(*in).DeepCopyInto(*out)
	}
	if in.Replace != nil {
		in, out := &in.Replace, &out.Replace
		*out = new(Replace)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtractTimestamp != nil {
		in, out := &in.ExtractTimestamp, &out.ExtractTimestamp
		*out = new(ExtractTimestamp)
		(*in).DeepCopyInto(*out)
	}
	if in.RemoveFields != nil {
		in, out := &in.RemoveFields, &out.RemoveFields
		*out = new(RemoveFields)
		(*in).DeepCopyInto(*out)
	}
	if in.JsonStringify != nil {
		in, out := &in.JsonStringify, &out.JsonStringify
		*out = new(JsonStringify)
		(*in).DeepCopyInto(*out)
	}
	if in.Extract != nil {
		in, out := &in.Extract, &out.Extract
		*out = new(Extract)
		(*in).DeepCopyInto(*out)
	}
	if in.ParseJsonField != nil {
		in, out := &in.ParseJsonField, &out.ParseJsonField
		*out = new(ParseJsonField)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rule.
func (in *Rule) DeepCopy() *Rule {
	if in == nil {
		return nil
	}
	out := new(Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroup) DeepCopyInto(out *RuleGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroup.
func (in *RuleGroup) DeepCopy() *RuleGroup {
	if in == nil {
		return nil
	}
	out := new(RuleGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupList) DeepCopyInto(out *RuleGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupList.
func (in *RuleGroupList) DeepCopy() *RuleGroupList {
	if in == nil {
		return nil
	}
	out := new(RuleGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupSpec) DeepCopyInto(out *RuleGroupSpec) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subsystems != nil {
		in, out := &in.Subsystems, &out.Subsystems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Severities != nil {
		in, out := &in.Severities, &out.Severities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Hidden != nil {
		in, out := &in.Hidden, &out.Hidden
		*out = new(bool)
		**out = **in
	}
	if in.Creator != nil {
		in, out := &in.Creator, &out.Creator
		*out = new(string)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(uint)
		**out = **in
	}
	if in.RuleSubgroups != nil {
		in, out := &in.RuleSubgroups, &out.RuleSubgroups
		*out = make([]RuleSubgroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupSpec.
func (in *RuleGroupSpec) DeepCopy() *RuleGroupSpec {
	if in == nil {
		return nil
	}
	out := new(RuleGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleGroupStatus) DeepCopyInto(out *RuleGroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleGroupStatus.
func (in *RuleGroupStatus) DeepCopy() *RuleGroupStatus {
	if in == nil {
		return nil
	}
	out := new(RuleGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleParams) DeepCopyInto(out *RuleParams) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(uint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleParams.
func (in *RuleParams) DeepCopy() *RuleParams {
	if in == nil {
		return nil
	}
	out := new(RuleParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleSubgroup) DeepCopyInto(out *RuleSubgroup) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = new(uint)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]Rule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleSubgroup.
func (in *RuleSubgroup) DeepCopy() *RuleSubgroup {
	if in == nil {
		return nil
	}
	out := new(RuleSubgroup)
	in.DeepCopyInto(out)
	return out
}
