# permissions for end users to view recordingrulegroupsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recordingrulegroupset-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coralogix-operator-poc
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kubernetes.io/managed-by: kustomize
  name: recordingrulegroupset-viewer-role
rules:
- apiGroups:
  - coralogix.coralogix
  resources:
  - recordingrulegroupsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coralogix.coralogix
  resources:
  - recordingrulegroupsets/status
  verbs:
  - get
