# permissions for end users to view rulegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rulegroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coralogix-operator-poc
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kubernetes.io/managed-by: kustomize
  name: rulegroup-viewer-role
rules:
- apiGroups:
  - coralogix.coralogix
  resources:
  - rulegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coralogix.coralogix
  resources:
  - rulegroups/status
  verbs:
  - get
