---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - coralogix.coralogix
  resources:
  - alerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.coralogix
  resources:
  - alerts/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.coralogix
  resources:
  - alerts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coralogix.coralogix
  resources:
  - rulegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.coralogix
  resources:
  - rulegroups/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.coralogix
  resources:
  - rulegroups/status
  verbs:
  - get
  - patch
  - update
