apiVersion: coralogix.coralogix/v1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator-poc
  name: alert-sample
spec:
  # TODO(user): Add fields here
