apiVersion: coralogix.com/v1alpha1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator-poc
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator-poc
  name: lucene-alert-example
spec:
  name: lucene alert example
  description: alert from k8s operator
  severity: Critical
  notifications:
    recipients:
      emails: ["user@example.com"]
      webhooks: ["WebhookAlerts"]
    notifyEveryMin: 30
  scheduling:
    daysEnabled: ["Wednesday", "Thursday"]
    timeZone: UTC+02
    startTime: 08:30
    endTime: 20:30
  alertType:
    metric:
      lucene:
        searchQuery: name:\"Frontend transactions\"
        conditions:
          metricField: subsystem
          arithmeticOperator: Percentile
          arithmeticOperatorModifier: 20
          alertWhen: Less
          groupBy: ["coralogix.metadata.sdkId"]
          threshold: 60
          sampleThresholdPercentage: 50
          timeWindow: ThirtyMinutes
          manageUndetectedValues:
            enableTriggeringOnUndetectedValues: false
