name: e2e-tests
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Install kuttl
        run: |
          curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.12.1/kubectl-kuttl_0.12.1_linux_x86_64
          chmod +x /usr/local/bin/kubectl-kuttl
      - name: Install CRDs
        run: make install
      - name: Tests
        run:  make e2e